FROM node:18-alpine

WORKDIR /node

COPY web .

# 安装所有依赖
RUN npm config set registry https://registry.npmmirror.com && \
    npm install

# 设置环境变量
ENV HOST=0.0.0.0
ENV PORT=8084
ENV API_URL=http://server:8091

# 使用开发模式
CMD ["npm", "run", "dev"]