FROM mysql:8.0-debian

# 设置环境变量（按需修改）
ENV MYSQL_ROOT_PASSWORD=abc123456
ENV MYSQL_DATABASE=xiaozhi
ENV MYSQL_USER=xiaozhi
ENV MYSQL_PASSWORD=123456

# 设置字符集和排序规则
ENV LANG=C.UTF-8
ENV MYSQL_CHARSET=utf8mb4
ENV MYSQL_COLLATION=utf8mb4_unicode_ci

# 复制SQL文件到初始化目录
COPY db/init.sql /docker-entrypoint-initdb.d/